name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm/v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: glebnaz
          password: ${{ secrets.TOKENGH }}
          registry: ghcr.io
      - name: Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/glebnaz/transmission-exporter:latest
            ghcr.io/glebnaz/transmission-exporter:${{ github.ref_name }}
          build-args: GITHUB_TOKEN=${{ secrets.TOKENGH }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.TOKENGH }}
